server:  port: 9000
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/user_registration
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:G:/KiranCodeBase/data
    username: sa
    password: password
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  flyway:
    baseline-on-migrate: true  cloud:    config:      enabled: false
logging:
  level:
    org.springframework.security.oauth2: trace
    org.springframework.boot.autoconfigure: error