apiVersion: v1
kind: ConfigMap
metadata:
  name: appointment-service
  namespace: db
data:
    postgres_host:  $(kubectl get svc/my-release-postgresql  -o jsonpath="{.spec.clusterIP}")
    application.properties: |-
      bean.message=Testing reload kiran ! Message from backend is: %s <br/> Services : %s
    